// <auto-generated />
namespace Clear.AccountManage.Infrastructure.EntityFramework
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V102));
        
        string IMigrationMetadata.Id
        {
            get { return "201801061032178_V1.0.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
