// <auto-generated />
namespace Clear.AccountManage.Infrastructure.EntityFramework
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V103));
        
        string IMigrationMetadata.Id
        {
            get { return "201801160712536_V1.0.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
